export const BTPS_ENV_KEYS = {
  SEED_USERS: 'BTPS_SEED_USERS',
  SEED_TRANSACTIONS: 'BTPS_SEED_TRANSACTIONS',
} as const;

export const DEFAULT_SEED_USERS_COUNT = 5;
export const DEFAULT_SEED_TRANSACTIONS_COUNT = 65;
